#:kivy 1.11.1

<DrawingSpace>:
  canvas.before:
    Color:
      rgba: 1, 0, 0, 1
    Rectangle:
      size: 100, 100
      pos: 10, 10
  canvas:
    Color:
      rgba: 0, 1, 0, 1
    Rectangle:
      size: 100, 100
      pos: 110, 10
  canvas.after:
    Color:
      rgba: 0, 0, 1, 1
    Rectangle:
      size: 100, 100
      pos: 210, 10
  Button:
    text: "Learning Portal for Kivy"
    size_hint: 1, 0.25
    pos_hint: { 'x' : .1, 'y' : .1}
