# File name: floatlayout.py

<Button>:
  color: 0, 1, 0, 1
  font_size: 32
  size_hint: 0.25, 0.25

<FloatLayout>:
  Button:
    text: "Django"
    pos_hint: {'x': 0, 'top': 1}
  Button:
    text: "Python"
    pos_hint: {'right': 1, 'y': 0}
  Button:
    text: "Java"
    pos_hint: {'center_x': 0.5, 'center_y': 0.5}
  CheckBox:
    color: 0, 1, 0, 1
    #size_hint_x: .2
    pos_hint: {'x':0.9, 'y':0.4}
    size_hint: 0.05, 0.05
    active: True
