#:kivy 1.11.1

<DrawingSpace>:
  pos_hint: {'x' : .5, 'y' : .5}
  canvas:
    Rectangle:
      source: 'appicon.png'
    Rotate:
      angle: 90
      axis: 0, 0, 1
    Color:
      rgb: 1, 0, 0
    Rectangle:
      source: 'appicon.png'
    Translate:
      x: -100
    Color:
      rgb: 0, 1, 0
    Rectangle:
      source: 'appicon.png'
    Translate:
      y: -100
    Scale:
      xyz: (.5, 0.5, 0)
    Color:
      rgb: 0, 0, 1
    Rectangle:
      source: 'appicon.png'
    
