# Generated by Django 2.1.5 on 2019-04-01 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('standard', models.IntegerField(default=0)),
                ('division', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Students'),
        ),
    ]
