#:kivy 1.11.1
#:import hex kivy.utils.get_color_from_hex

<MyBoxLayout@BoxLayout>:
  orientation: 'vertical'
  padding: 50, 50, 50, 50
  #size: root.size
  #pos: root.pos

<Manager>:
  result: "msg"
  percentage: "per"
  #size: root.size
  #pos: root.pos
  canvas:
    Color:
      rgba: hex('#9B1B30')
    Rectangle:
      pos: self.pos
      size: self.size
      source: 'seaside-forest.jpg'

  Screen:
    name: 'start'
    MyBoxLayout:
      Label:
        text: "Relationships are precious. It may be between anyone. Please hold them tight and respect each other."
        font_size: 100
        valign: "middle"
        text_size: self.size
        color: hex('#FFFFFF')
        size_hint: .5, .5
      Button:
        text: "Start"
        color: hex('#FFFFFF')
        background_color: hex('#926F5B')
        size_hint: .5, .5
        pos_hint: {'center_x':.5, 'y':.2}
        font_size: 32
        on_press:
          root.playstart()
          app.sm.current = 'first'

  Screen:
    name: 'first'
    MyBoxLayout:
      GridLayout:
        cols: 1
        Label:
          text: "First Name"
          bold: True
          font_size: 32
          color: hex('#FFFFFF')
        ValidateInput:
          id: firstname
          multiline: False
          text: ""
          hint_text: "Insert alphabets only"
          on_text:
            self.readonly = True if len(self.text.strip()) == 15 else False
          font_size: 32
        Label:
          text: "Second Name"
          bold: True
          color: hex('#FFFFFF')
          font_size: 32
        ValidateInput:
          id: secondname
          multiline: False
          text: ""
          hint_text: "Insert Alphabets only"
          on_text:
            self.readonly = True if len(self.text.strip()) == 15 else False
          font_size: 32
      Button:
        text: "Submit"
        color: hex('#FFFFFF')
        background_color: hex('#926F5B')
        size_hint: 0.5, 0.2
        pos_hint: {'center_x':.5, 'y':.2}
        font_size: 32
        on_press:
          root.results()
          app.sm.current = 'other'

  Screen:
    name: 'other'
    MyBoxLayout:
      GridLayout:
        cols: 1
        Label:
          text: "Your Compatibility"
          underline: True
          bold: True
          color: hex('#FFFFFF')
          font_size: 32
        Label:
          id: per
          text: str(root.percentage) + '%'
          font_size: 32
        Label:
          text: "Advice"
          underline: True
          bold: True
          color: hex('#FFFFFF')
          font_size: 32
        Label:
          id: msg
          font_size: 32
          text: str(root.result)
      Button:
        text:'Return'
        color: hex('#FFFFFF')
        background_color: hex('#926F5B')
        font_size: 32
        size_hint: 0.5, 0.2
        pos_hint: {'center_x':.5, 'y':.2}
        on_press:
          app.sm.current = 'first'
