#:kivy 1.11.1

<RectBlock>:
    canvas:
        Rectangle:
            size: 100, 50
            pos: self.pos

<TestGame>:
    block: Rect_Block
    Button:
        text: "top"
        size: 100, 50
        pos: root.center_x - 50, root.top - 50
        on_press:
            print("Top Button Pressed")
            root.moveTop()
            root.block.pushTop()
    Button:
        text: "Left"
        size: 100, 50
        pos: root.x, root.top - 50
        on_press:
            print("Left Button Pressed")
            root.moveLeft()
            root.block.pushLeft()
    Button:
        text: "Right"
        size: 100, 50
        pos: root.right - 100, root.top - 50
        on_press:
            print("Right Button Pressed")
            root.moveRight()
            root.block.pushRight()
    Button:
        text: "bottom"
        size: 100, 50
        pos: root.center_x - 50, 0
        on_press:
            print("Bottom Button Pressed")
            root.moveBottom()
            root.block.pushBottom()
    RectBlock:
        id: Rect_Block
        center: self.parent.center 
